M48
; DRILL file {KiCad 6.0.2-378541a8eb~116~ubuntu20.04.1} date Mi 16 Feb 2022 17:00:27 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-02-16T17:00:27+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2-378541a8eb~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
%
G90
G05
T1
X106.6Y-31.776
X106.6Y-36.176
T0
M30
